local cmd = vim.cmd

-- cmd.nocompatible=true
-- cmd.filetype = false
-- cmd.syntax = true
-- cmd.number = true
-- cmd.laststatus=2
-- cmd.noswapfile = true
-- cmd.autoread = true
-- cmd.noshowmode = true
-- cmd.belloff=all
-- cmd.noerrorbells = true
-- cmd.visualbell = true
-- cmd.encoding='UTF-8'
-- cmd.bg='dark'
-- cmd.background='dark'
-- cmd.base16colorspace=256
-- cmd.backspace = 'indent,eol,start'
-- cmd.tabstop=2
-- cmd.softtabstop=2
-- cmd.shiftwidth=2
-- cmd.noexpandtab = true
-- cmd.splitbelow = true
-- cmd.splitright = true
-- cmd.relativenumber = true
-- cmd.incsearch = true
-- cmd.noerrorbells = true
-- cmd.nowrap = true
-- cmd.maxmempattern = 20000
-- cmd.ttimeout = true
-- cmd.ttimeoutlen=100
-- cmd.timeoutlen=3000
-- cmd.t_Co=256
-- cmd.termguicolors=true

-- cmd('let g:gruvbox_contrast_dark="hard"')
-- cmd('let g:gruvbox_contrast_light="hard"')
-- cmd('hi Visual term=reverse cterm=reverse guibg=White')
-- cmd('filetype plugin on')

-- cmd('colorscheme kanagawa-dragon')
-- cmd('highlight StatusLine cterm=NONE ctermbg=black ctermfg=white guibg=#000000 guifg=#ffffff')
-- cmd([[autocmd BufNewFile,BufRead *.v set filetype=v]])
-- cmd([[highlight link TelescopeSelection Search]])
